name: gve-lrcn
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - cython=0.29.12
  - future=0.17.1
  - matplotlib=3.1.0
  - numpy=1.16.4
  - openjdk=8.0.152
  - pillow=6.1.0
  - pip=19.1.1
  - python=3.7.3
  - pytorch=1.1.0
  - tensorboard=1.14.0
  - torchvision=0.3.0
  - pip:
    - git+https://github.com/salaniz/pycocoevalcap
    - pycocotools==2.0.0
